# Generated by Django 4.2.5 on 2024-01-27 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanproapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='loanapplicant',
            name='email',
            field=models.EmailField(default='abc@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='loanapplicant',
            name='loan_amount_requested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanapplicant',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanapplicant',
            name='purpose_of_loan',
            field=models.TextField(default='sample'),
        ),
    ]
