# Generated by Django 4.2.5 on 2024-01-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanproapp', '0002_loanapplicant_date_of_birth_loanapplicant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicant',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loanapplicant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='loanapplicant',
            name='loan_amount_requested',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanapplicant',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanapplicant',
            name='purpose_of_loan',
            field=models.TextField(),
        ),
    ]
